DROP DATABASE IF EXISTS ChildDaycare;

CREATE DATABASE ChildDaycare;

USE ChildDaycare;


CREATE TABLE IF NOT EXISTS DAYCARE (
     DaycareName VARCHAR(100) NOT NULL
   , DaycareAddress VARCHAR(100) NOT NULL
   , TotalNumOfCaretakers INT
   , CONSTRAINT PK_Daycare PRIMARY KEY (DaycareName, DaycareAddress)
);

CREATE TABLE IF NOT EXISTS PERSON (
     SIN INT NOT NULL
   , Name VARCHAR(30)
   , Gender VARCHAR(30)
   , Address VARCHAR(50)
   , constraint pk_person PRIMARY KEY (SIN)
);

DROP TABLE IF EXISTS PERSON_PHONE;
CREATE TABLE PERSON_PHONE (
	SIN INT NOT NULL,
	PhoneNum INT NOT NULL,
	CONSTRAINT PK_PERSONPHONE PRIMARY KEY (SIN, PhoneNum)
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN)
);

DROP TABLE IF EXISTS PARENT_GUARDIAN;
CREATE TABLE PARENT_GUARDIAN (
	SIN int NOT NULL,
	CaretakerEmployeeId INT,
	BillId INT,
	CONSTRAINT PK_PARENT PRIMARY KEY (SIN, CaretakerEmployeeId, BillId),
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN),
	CONSTRAINT CaretakerEmployeeId FOREIGN KEY (CaretakerEmployeeId) REFERENCES CARETAKER (EMPLOYEEID),
	CONSTRAINT BILLID FOREIGN KEY (BILLID) REFERENCES BILL (BILLID)
);

DROP TABLE IF  EXISTS CHILD;
CREATE TABLE CHILD (
	SIN INT NOT NULL,
	CARETAKEREMPLOYEEID INT NOT NULL,
	PARENTSIN INT NOT NULL,
	RoomId INT NOT NULL,
	DateOfBirth DATE NOT NULL,
	CONSTRAINT PK_CHILD PRIMARY KEY (SIN, CARETAKEREMPLOYEEID, PARENTSIN,ROOMID),
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN),
	CONSTRAINT CaretakerEmployeeId FOREIGN KEY (CaretakerEmployeeId) REFERENCES CARETAKER (EMPLOYEEID),
	CONSTRAINT PARENTSIN FOREIGN KEY (PARENTSIN) REFERENCES PARENT_GUARDIAN (SIN),
	CONSTRAINT ROOMID FOREIGN KEY (ROOMID) REFERENCES ROOM (ROOMID)
);

DROP TABLE IF EXISTS CONDITION;
CREATE TABLE CONDITION (
	CHILDSIN INT NOT NULL,
	CONDITIONNAME VARCHAR(100) NOT NULL,
	CONDITIONTREATMENT VARCHAR(100) NOT NULL
	CONSTRAINT PK_CONDITION PRIMARY KEY (CHILDSIN, CONDITIONNAME, CONDITIONTREATMENT),
	CONSTRAINT CHILD SIN FOREIGN KEY (CHILDSIN) REFERENCES CHILD (SIN)
);

DROP TABLE IF EXISTS BILL;
CREATE TABLE BILL (
	BILLID INT NOT NULL,
	CREATEDBYID INT NOT NULL,
	PAYMENTMETHOD VARCHAR(30),
	AMOUNTPENDING INT NOT NULL,
	CONSTRAINT pk_bill PRIMARY KEY (BILLID, CREATEDBYID),
	CONSTRAINT CREATEDBYID FOREIGN KEY (CREATEDBYID) REFERENCES ADMIN (EMPLOYEEID)
);


DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE (
	DAYCARENAME VARCHAR(100) NOT NULL,
	DaycareAddress VARCHAR(100) NOT NULL,
	SIN INT NOT NULL,
	EMPLOYEEID INT NOT NULL,
	StartDate DATE,
	WORKHOURS VARCHAR(100),
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY (DAYCARENAME, DAYCAREADDRESS, SIN, EMPLOYEEID),
	CONSTRAINT DAYCARENAME FOREIGN KEY (DAYCARENAME) REFERENCES DAYCARE (DAYCARENAME),
	CONSTRAINT DAYCAREADDRESS FOREIGN KEY (DAYCAREADDRESS) REFERENCES DAYCARE (DAYCAREADDRESS),
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN)
);

DROP TABLE IF EXISTS ADMIN;
CREATE TABLE ADMIN (
	SIN INT NOT NULL,
	EMPLOYEEID INT NOT NULL,
	CONSTRAINT PK_ADMIN PRIMARY KEY (SIN, EMPLOYEEID),
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN),
	CONSTRAINT EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID)
);

DROP TABLE IF EXISTS CARETAKER;
CREATE TABLE CARETAKER (
	SIN INT NOT NULL,
	EMPLOYEEID INT NOT NULL,
	AVAILABILITY VARCHAR(100),
	CONSTRAINT PK_CARETAKER PRIMARY KEY (SIN, EMPLOYEEID),
	CONSTRAINT SIN FOREIGN KEY (SIN) REFERENCES PERSON (SIN),
	CONSTRAINT EMPLOYEEID FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID)
);

DROP TABLE IF EXISTS WAITLIST;
CREATE TABLE WAITLIST (
	CHILDNAME VARCHAR(100) NOT NULL,
	FAMILYNAME VARCHAR(100) NOT NULL,
	SUBMITTEDBYID INT NOT NULL,
	CONSTRAINT PK_WAITLIST PRIMARY KEY (CHILDNAME, FAMILYNAME, SUBMITTEDBYID),
	CONSTRAINT SUBMITTEDBYID FOREIGN KEY (SUBMITTEDBYID) REFERENCES ADMIN (EMPLOYEEID)
);

DROP TABLE IF EXISTS CARETAKER_SPECIALIZATION;
CREATE TABLE CARETAKER_SPECIALIZATION (
	CARETAKERSIN INT NOT NULL,
	SPECIALIZATIONTYPE VARCHAR(100) NOT NULL,
	CONSTRAINT PK_CSPEC PRIMARY KEY (CARETAKERSIN, SPECIALIZATIONTYPE),
	CONSTRAINT CARETAKERSIN FOREIGN KEY (CARETAKERSIN) REFERENCES CARETAKER (SIN)
);

DROP TABLE IF EXISTS ROOM;
CREATE TABLE ROOM (
	DAYCARENAME VARCHAR(100) NOT NULL,
	DAYCAREADDRESS VARCHAR(100) NOT NULL,
	ROOMID INT NOT NULL,
	SEATSAVAILABLE INT NOT NULL,
	CONSTRAINT PK_ROOM PRIMARY KEY (DAYCARENAME, DAYCAREADDRESS, ROOMID),
	CONSTRAINT DAYCARENAME FOREIGN KEY (DAYCARENAME) REFERENCES DAYCARE (DAYCARENAME),
	CONSTRAINT DAYCAREADDRESS FOREIGN KEY (DAYCAREADDRESS) REFERENCES DAYCARE (DAYCAREADDRESS)
);

DROP TABLE IF EXISTS DAILY_REPORT;
CREATE TABLE DAILY_REPORT (
	CHILDSIN INT NOT NULL,
	DATE DATE NOT NULL,
	REPORTID INT NOT NULL,
	CARETAKEREMPLOYEEID INT NOT NULL,
	STARTTIME DATETIME,
	ENDTIME DATETIME,
	REPORTCOMMENT VARCHAR(100),
	CONSTRAINT PK_REPORT PRIMARY KEY (CHILDSIN, DATE, REPORTID, CARETAKEREMPLOYEEID),
	CONSTRAINT CHILDSIN FOREIGN KEY (CHILDSIN) REFERENCES CHILD (SIN),
	CONSTRAINT CARETAKERID FOREIGN KEY (CARETAKEREMPLOYEEID) REFERENCES CARETAKER (EMPLOYEEID)
);

DROP TABLE IF EXISTS INCIDENTS;
CREATE TABLE INCIDENTS (
	REPORTID INT NOT NULL,
	ACTIONREQUIRED VARCHAR(100),
	CONSTRAINT PK_INCID PRIMARY KEY (REPORTID),
	CONSTRAINT REPORTID FOREIGN KEY (REPORTID) REFERENCES DAILY_REPORT (REPORTID)
);

DROP TABLE IF EXISTS ACTIVITIES;
CREATE TABLE ACTIVITIES (
	REPORTID INT NOT NULL,
	LESSONSLEARNED VARCHAR(100),
	CONSTRAINT PK_ACT PRIMARY KEY (REPORTID),
	CONSTRAINT REPORTID FOREIGN KEY (REPORTID) REFERENCES DAILY_REPORT (REPORTID)
);




INSERT INTO PERSON VALUES (123456789, 'Erin', 'Female', '123 Calgary Drive'),(111222333, 'Joe Fresh', 'Male','Also Clagary Dr'), (111111111, 'First Child', 'Female', 'Home address'), (111111112, 'Child Parent', 'Male', 'Home address');































